---
title: "Exploratory analysis; interactive plots"
author: "Dereck de Mézquita"
date: "`r format(Sys.time(), '%d %B, %Y')`"
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), "./reports/", "/exploratory-analysis-interactive/exploratory-analysis-interactive.html")) })
output:
  html_document: 
    fig_caption: yes
    keep_md: yes
    number_sections: yes
    toc: yes
    toc_float: yes
    # code_folding: hide
params:
  rmd: exploratory-analysis-interactive.Rmd
editor_options: 
  chunk_output_type: inline
---

<a download="exploratory-analysis-interactive.Rmd" href="`r base64enc::dataURI(file = params$rmd, mime = 'text/rmd', encoding = 'base64')`">R Markdown source file (to produce this document)</a>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dpi = 250, fig.width = 10, fig.height = 10, fig.align = "center")
```

# Libraries

```{r libraries, warning=FALSE, message=FALSE}
library("tidyverse")
options(dplyr.summarise.inform = FALSE)
# theme_set(theme(legend.position = "none"))
library("plotly")
library("countrycode")
```

```{r}
{data$gdp %>%
	filter(!is.na(gdp)) %>%
	ggplot(aes(year, gdp, group = code, colour = region7)) +
	geom_line() +
	theme(legend.position = "none")} %>% ggplotly()
```

```{r pop-line-world-int, fig.width=10, fig.height=10, warning=FALSE}
{data$pop %>%
	ggplot(aes(year, population, group = country, colour = code)) +
	geom_line() +
	geom_vline(xintercept = 2020, linetype = "dotted", colour = "red") +
	scale_y_continuous(trans = "log2", n.breaks = 10, labels = function(x) {
		scales::label_number_si(accuracy = 0.1)(x)
	}) +
	theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) + # legend.position = "none",
	labs(title = "World population per region", subtitle = "Red dotted line: projected", x = "Year", y = "Population log2") +
	lemon::facet_rep_wrap(~ region7, scales = "fixed", repeat.tick.labels = TRUE)} %>%
	plotly::ggplotly()
```

```{r pop-line-per-total-sums-int, fig.width=10, fig.height=10}
p <- data$pop %>%
	group_by(year) %>%
	summarise(population = sum(population)) %>%
	mutate(colour = ifelse(year <= 2020, "#444444", "red"),
			 type = ifelse(year <= 2020, "solid", "dashed")) %>%
	ggplot(aes(year, population, colour = colour, linetype = type)) +
	geom_line() +
	geom_vline(xintercept = 2020, linetype = "dotted", colour = "red") +
	scale_color_identity() +
	scale_linetype_identity() +
	scale_y_continuous(n.breaks = 10, labels = function(x) {
		scales::label_number_si(accuracy = 0.1)(x)
	}) +
	labs(title = "World population", subtitle = "Red dotted line: projected", x = "Year", y = "Population (Billions)") +
	theme(legend.position = "none")

p

ggplotly(p)
```


```{r w4-women-held-line-int, fig.width=10, fig.height=10}
{data$world_4region %>%
	select(Region, Year, wn_bothhouses_c) %>%
	rename(Value = wn_bothhouses_c) %>%
	mutate(Region = stringr::str_to_title(Region)) %>%
	ggplot(aes(Year, Value, colour = Region)) +
	geom_line() +
	scale_x_continuous(n.breaks = 20) +
	scale_y_continuous(n.breaks = 10, labels = function(x) paste0(x, "%")) + # Add percent sign
	theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
	labs(title = "Percentage of parliamentary seats held by women", x = "Year", y = "Women held parliamentary seats %") +
	scale_colour_discrete(name = "World region")} %>%
	ggplotly()
```



```{r w4-refugee-line-int, fig.width=10, fig.height=10,}
{data$world_4region %>%
	select(Region, Year, refugee_in_perc_wb) %>%
	rename(Value = refugee_in_perc_wb) %>%
	filter(!is.na(Value)) %>%
	ggplot(aes(Year, Value, colour = Region)) +
	geom_line() +
	scale_x_continuous(n.breaks = 20) +
	scale_y_continuous(n.breaks = 10, labels = function(x) paste0(x, "%")) + # Add percent sign
	theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
	labs(title = "Percentage of refugees to total population of origin", x = "Year", y = "Refugees to total population of origin %") +
	scale_colour_discrete(name = "World region")} %>%
	ggplotly()
```



```{r w4-hiv-deaths-line-int, fig.width=10, fig.height=10}
{data$world_4region %>%
	select(Region, Year, ihme_hiv_death) %>%
	rename(Value = ihme_hiv_death) %>%
	filter(!is.na(Value)) %>%
	ggplot(aes(Year, Value, colour = Region)) +
	geom_line() +
	scale_x_continuous(n.breaks = 20) +
	scale_y_continuous(n.breaks = 10, labels = function(x) paste0(x, "%")) + # Add percent sign
	theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
	labs(title = "Proportion of HIV/AIDS deaths", x = "Year", y = "Proportion of HIV/AIDS deaths %") +
	scale_colour_discrete(name = "World region")} %>%
	ggplotly()
```


```{r w4-hiv-deaths-log-line-int}
{data$world_4region %>%
	select(Region, Year, ihme_hiv_death) %>%
	rename(Value = ihme_hiv_death) %>%
	filter(!is.na(Value)) %>%
	ggplot(aes(Year, Value, colour = Region)) +
	geom_line() +
	scale_x_continuous(n.breaks = 20) +
	scale_y_continuous(trans = "log2", n.breaks = 10, labels = function(x) paste0(x, "%")) + # Add percent sign
	theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
	labs(title = "Proportion of HIV/AIDS deaths", x = "Year", y = "Proportion of HIV/AIDS deaths %") +
	scale_colour_discrete(name = "World region")} %>%
	ggplotly()
```



```{r w4-conflict-death-line-int, fig.width=10, fig.height=10,}
{data$world_4region %>%
	select(Region, Year, ihme_conflict_death) %>%
	rename(Value = ihme_conflict_death) %>%
	filter(!is.na(Value)) %>%
	ggplot(aes(Year, Value, colour = Region)) +
	geom_line() +
	scale_x_continuous(n.breaks = 20) +
	scale_y_continuous(n.breaks = 10, labels = function(x) paste0(x, "%")) + # Add percent sign
	theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
	labs(title = "Proportion of conflict/terrorism deaths", x = "Year", y = "Proportion of conflict/terrorism deaths %") +
	scale_colour_discrete(name = "World region")} %>%
	ggplotly()
```




```{r w4-conflict-death-log-line-int, fig.width=10, fig.height=10,}
{data$world_4region %>%
	select(Region, Year, ihme_conflict_death) %>%
	rename(Value = ihme_conflict_death) %>%
	filter(!is.na(Value)) %>%
	ggplot(aes(Year, Value, colour = Region)) +
	geom_line() +
	scale_x_continuous(n.breaks = 20) +
	scale_y_continuous(trans = "log2", n.breaks = 15, labels = function(x) paste0(round(x, digits = 5), "%")) + # Add percent sign
	theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
	labs(title = "Proportion of conflict/terrorism deaths", x = "Year", y = "Proportion of conflict/terrorism deaths % (log2)") +
	scale_colour_discrete(name = "World region")} %>%
	ggplotly()
```


```{r w4-cardio-deaths-line-int, fig.width=10, fig.height=10,}
{data$world_4region %>%
	select(Region, Year, ihme_cardio_death) %>%
	rename(Value = ihme_cardio_death) %>%
	filter(!is.na(Value)) %>%
	ggplot(aes(Year, Value, colour = Region)) +
	geom_line() +
	scale_x_continuous(n.breaks = 20) +
	scale_y_continuous(n.breaks = 10, labels = function(x) paste0(x, "%")) + # Add percent sign
	theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
	labs(title = "Proportion of cardiovascular disease deaths", x = "Year", y = "Proportion of cardiovascular disease deaths %") +
	scale_colour_discrete(name = "World region")} %>%
	ggplotly()
```