---
title: "Create logo"
author: "Dereck de Mézquita"
date: "`r format(Sys.time(), '%d %B, %Y')`"
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), "./reports/", "/project-logo/project-logo.html")) })
output:
  html_document: 
    fig_caption: yes
    keep_md: yes
    number_sections: yes
    toc: yes
    # toc_float: yes
    # code_folding: hide
params:
  rmd: project-logo.Rmd
editor_options: 
  chunk_output_type: inline
---

<a download="project-logo.Rmd" href="`r base64enc::dataURI(file = params$rmd, mime = 'text/rmd', encoding = 'base64')`">R Markdown source file (to produce this document)</a>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dpi = 500, fig.width = 8, fig.height = 8, fig.align = "center")
```

# Libraries

```{r libraries, warning=FALSE, message=FALSE}
library("tidyverse")
options(dplyr.summarise.inform = FALSE)
# theme_set(theme(legend.position = "none"))
library("countrycode")
library("scales")

library("ddplot")
```

# ggplot theme

```{r set-ggplot-defaults}
update_geom_defaults("line", list(alpha = 0.65, size = 0.65))

theme_set(theme_dereck())
```

# Load data

```{r load-data}
data <- readRDS("./outputs/gapminder/clean_data.Rds")
```

```{r project-logo}
data$merged %>% 
	select(region7geoEU, Code, Year, u5pop, pop_total) %>%
	filter(!is.na(u5pop) & !is.na(pop_total)) %>%
	mutate(Value = ((u5pop / pop_total) * 100)) %>%
	filter(!is.na(Value)) %>%
	ggplot(aes(Year, Value, group = Code, colour = region7geoEU)) +
	geom_line(alpha = 0.4, size = 0.95) +
	geom_vline(xintercept = 2020, colour = "red", linetype = "dashed") +
	directlabels::geom_dl(aes(label = Code), method = list(directlabels::dl.trans(x = x + 0.2), "last.points", cex = 0.65, alpha = 0.65)) +
	directlabels::geom_dl(aes(label = Code), method = list(directlabels::dl.trans(x = x - 0.2), "first.points", cex = 0.65, alpha = 0.65)) +
	scale_x_continuous(n.breaks = 20, expand = expansion(mult = c(0.1, 0.1))) +
	scale_y_continuous(n.breaks = 20, labels = function(x) {
		paste0(x, "%")
	}) + # Add percent sign
	guides(color = guide_legend(override.aes = list(alpha = 0.95))) + # make alpha coloured legend darker
	theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), legend.title = element_text(vjust = 0.5)) +
	labs(title = "Percentage to country's population of children 0 - 5 yrs", subtitle = "Coloured by region", x = "Year", y = "Percent of children under 5 yrs", colour = "Region", caption = "By Dereck de Mezquita")
```

```{r}
p <- data$merged %>% 
	select(region7geoEU, Code, Year, u5pop, pop_total) %>%
	filter(!is.na(u5pop) & !is.na(pop_total)) %>%
	mutate(Value = ((u5pop / pop_total) * 100)) %>%
	filter(!is.na(Value)) %>%
	ggplot(aes(Year, Value, group = Code, colour = region7geoEU)) +
	geom_line(alpha = 0.65, size = 2.5) +
	geom_vline(xintercept = 2020, colour = "red", linetype = "dashed", size = 2.5) +
	# directlabels::geom_dl(aes(label = Code), method = list(directlabels::dl.trans(x = x + 0.2), "last.points", cex = 0.65, alpha = 0.65)) +
	# directlabels::geom_dl(aes(label = Code), method = list(directlabels::dl.trans(x = x - 0.2), "first.points", cex = 0.65, alpha = 0.65)) +
	scale_x_continuous(n.breaks = 20, expand = expansion(mult = c(0.1, 0.1))) +
	scale_y_continuous(n.breaks = 20) + # Add percent sign
	theme(legend.position = "none",
			axis.title.x = element_blank(),
			axis.title.y = element_blank(),
			axis.text.x = element_blank(),
			axis.text.y = element_blank(),
			legend.title = element_blank(),
			panel.grid.major = element_blank(),
			panel.grid.minor = element_blank(),
			axis.ticks = element_blank(),
			rect = element_rect(fill = "transparent"),
			panel.background = element_rect(fill = "transparent"), # bg of the panel
			plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
			legend.background = element_rect(fill = "transparent"), # get rid of legend bg
			legend.box.background = element_rect(fill = "transparent")) # get rid of legend panel bg

ggsave(p, filename = "../images/project-logo.png", bg = "transparent")
```


