---
title: "Scrape wars data"
author: "Dereck de Mézquita"
date: "2/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, message=FALSE}
library("tidyverse")
library("xml2")

library("rvest")
```

```{r}
scrape_wars_tables <- function(x) {
	return(html_table(read_html(x), fill = TRUE))
}
```

# All wars

```{r}
data <- lapply(c("https://en.wikipedia.org/wiki/List_of_wars:_1900–1944",
					  "https://en.wikipedia.org/wiki/List_of_wars:_1945–1989",
					  "https://en.wikipedia.org/wiki/List_of_wars:_1990–2002",
					  "https://en.wikipedia.org/wiki/List_of_wars:_2003–present"), scrape_wars_tables)

data <- unlist(data, recursive = FALSE)

data[c(4, 10, 12, 14, 15)] <- NULL

data <- lapply(data, function(x) {
	colnames(x) <- c("start", "finish", "conflict_name", "victor", "loser")
	x <- as.data.frame(x)
	x <- x[-1, ]
	return(x)
})

data <- do.call(rbind, data)
```

```{r}
month.name
unique(data$start); length(data$start)
unique(regmatches(data$start, regexpr("[0-9]{4}", data$start))); length(regmatches(data$start, regexpr("[0-9]{4}", data$start)))
unique(data$finish); length(data$finish)
unique(regmatches(data$finish, regexpr("[0-9]{4}", data$finish))); length(regmatches(data$finish, regexpr("[0-9]{4}", data$finish)))
```

```{r}
gsub_war_text <- function(x) {
	return(trimws(gsub("\\[[0-9]+\\]|\\[[a-z]+\\]", " ", gsub(" +", " ", gsub("\\\n", " ", x)))))
}
```

```{r}
data <- data %>%
	mutate(start = regmatches(start, regexpr("[0-9]{4}", start)),
			 finish = ifelse(finish %in% c("Ongoing", "Ongoing\n[Stalemate in 1953]", "Present"), "2021", finish)) %>%
	mutate(finish = regmatches(finish, regexpr("[0-9]{4}", finish))) %>%
	mutate(conflict_name = gsub_war_text(conflict_name),
			 victor = gsub_war_text(victor),
			 loser = gsub_war_text(loser))


write.csv(data, "./outputs/scrape/clean_wars_scrape.csv", row.names = FALSE)
```

# American wars

```{r}
data <- scrape_wars_tables("https://en.wikipedia.org/wiki/United_States_military_casualties_of_war")

data <- data.frame(unlist(data[5], recursive = FALSE))

str(data)

colnames(data) <- c("rank", "war", "years", "deaths", "deats_per_day", "us_pop_1st_yr_of_war", "deaths_prc_pop")

data %>% 
	separate(col = years, into = c("start", "finish"), sep = "–") %>%
	mutate(finish = ifelse(nchar(finish) == 2, glue::glue("19{finish}"), finish),
			 deaths = gsub("\\(.*\\)+|\\[.*\\]", "", deaths)) %>%
	mutate(finish = ifelse(finish == "present", "2021", finish)) %>%
	mutate(finish = ifelse(is.na(finish), start, finish)) %>%
	lapply(function(x) {
		gsub(",|%", "", x)
	}) %>% as.data.frame() %>%
	write.csv("./outputs/scrape/clean_usa_wars_scrape.csv", row.names = FALSE)
```


