---
title: "USA: vote dataset preprocessing"
author: "Dereck de Mézquita"
date: "`r format(Sys.time(), '%d %B, %Y')`"
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), "./reports/", "us-county-vote-dataset-preprocessing/us-county-vote-dataset-preprocessing.html")) })
output:
  html_document: 
    fig_caption: yes
    keep_md: yes
    number_sections: yes
    toc: yes
    toc_float: yes
params:
  rmd: us-county-vote-dataset-preprocessing.Rmd
editor_options: 
  chunk_output_type: inline
---

<a download="us-county-vote-dataset-preprocessing.Rmd" href="`r base64enc::dataURI(file = params$rmd, mime = 'text/rmd', encoding = 'base64')`">R Markdown source file (to produce this document)</a>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, out.width = "100%", out.height = "60vh", fig.align = "center")
```

# Libraries

```{r warning=FALSE, message=FALSE}
library("tidyverse")
library("tidycensus")
```

```{r}
clr <- list(
	rouge = "#e32b2b",
	bleu = "#2b5ce3",
	neutre = "#777777"
)
```


# County data

```{r}
data("fips_codes")

fips_codes <- fips_codes %>%
   mutate(fips = as.character(paste0(state_code, county_code))) %>%
   select(fips, state, state_name, county)

colnames(fips_codes) <- c("fips", "abbrv", "state", "county")
```

# Kaggle

```{r}
fontes <- lapply(list.files("./data/united-states-of-america/per-county-votes-20-fontes/", full.names = TRUE), read.csv)
names(fontes) <- gsub(".csv", "", list.files("./data/united-states-of-america/per-county-votes-20-fontes/"), perl = TRUE)
```

```{r}
prsdnt <- inner_join(fips_codes, fontes$president_county_candidate, by = c("state", "county"))
```

```{r}
prsdnt %>%
  mutate(party = ifelse(party %in% c("REP", "DEM"), party, "Other"),
         colour = case_when(party == "REP" ~ clr$rouge, party == "DEM" ~ clr$bleu, TRUE ~ clr$neutre)) %>%
  group_by(fips) %>%
  mutate(new_total_votes = sum(total_votes))
```


# tonmcg

## General election presidential per county; tonmcg

```{r}

```

