---
title: "Choropleth; USA counties"
author: "Dereck de Mézquita"
date: "`r format(Sys.time(), '%d %B, %Y')`"
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), "./reports/", "us-county-choropleths/us-county-choropleths.html")) })
output:
  html_document: 
    fig_caption: yes
    keep_md: yes
    number_sections: yes
    toc: yes
    toc_float: yes
params:
  rmd: us-county-choropleths.Rmd
editor_options: 
  chunk_output_type: inline
---

<a download="us-county-choropleths.Rmd" href="`r base64enc::dataURI(file = params$rmd, mime = 'text/rmd', encoding = 'base64')`">R Markdown source file (to produce this document)</a>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dpi = 500, fig.width = 8, fig.height = 8, fig.align = "center")
```

# Libraries

```{r libraries, warning=FALSE, message=FALSE}
library("tidyverse")
# Suppress summarise info
options(dplyr.summarise.inform = FALSE)

library("plotly")
library("leaflet")

library("geojsonio")
library("sp")
library("broom")

library("viridis")
```

# Load data

```{r load-data}
# data <- read.csv("./outputs/united-states-of-america/processed-data/all-merged-data.csv", row.names = 1)
data <- lapply(list.files("./outputs/united-states-of-america/", pattern = "\\.csv$", full.names = TRUE), read.csv)
names(data) <- gsub("\\.csv$", "", list.files("./outputs/united-states-of-america/", pattern = "\\.csv$"))
```

```{r dataset-names}
names(data)
```

```{r join-location-data}
data <- lapply(data, function(x) {
  Reduce(function(...) {
    merge(..., all.x = TRUE)
  }, list(data$fip_codes, x))
})
```

# Choropleth; map making with R

- Per state: "https://raw.githubusercontent.com/deldersveld/topojson/master/countries/united-states/us-albers.json"
- Per county: "https://raw.githubusercontent.com/deldersveld/topojson/master/countries/united-states/us-albers-counties.json"

## Download counties geoJSON USA

```{r download-usa-geojson}
if(!file.exists("./outputs/mapping-data/us-albers-counties.json")) {
  download.file("https://raw.githubusercontent.com/deldersveld/topojson/master/countries/united-states/us-albers-counties.json", "./outputs/mapping-data/us-albers-counties.json")
}

usa <- geojsonio::geojson_read("./outputs/mapping-data/us-albers-counties.json", what = "sp")

plot(usa)
```

```{r geojson-to-tidy, warning=FALSE, message=FALSE}
usa_tdy <- broom::tidy(usa, region = "fips")

usa_tdy %>%
  ggplot() +
  geom_polygon(aes(x = long, y = lat, group = group), fill = "white", color = "grey") +
  theme_void() +
  coord_map()
```

```{r func-choroplot}
choroplot <- function(data, value = NULL, colour = "black", size = 0.075, alpha = 0.9, trans = "log10", length.out = 3, title = "", guide_title = "", caption = "") {
  # if(!any(colnames(usa_pop) == "value")) {stop("Must contain column named 'values'.")}
  data %>%
    ggplot() +
    geom_polygon(aes(x = long, y = lat, group = group, fill = data[,value]), colour = colour, size = size, alpha = alpha) +
    # geom_polygon(aes(x = long, y = lat, group = group), size = 0.075, colour = "black", alpha = 0) +
    theme_void() +
    scale_fill_viridis(trans = trans,
                       breaks = seq(0, max(data[,value]), length.out = length.out), # seq(0, max(usa_pop$value), by = 1000000)
                       name = guide_title,
                       guide = guide_legend(keyheight = unit(2, units = "mm"), 
                                            keywidth = unit(5, units = "mm"), 
                                            label.position = "bottom", 
                                            title.position = 'top', 
                                            nrow = 1),
                       label = function(x) {
                         format(x, big.mark = ",", scientific = FALSE)
                         }) +
    labs(title = title,
         # subtitle = "Population per county",
         caption = caption) +
    theme(# text = element_text(color = "#22211d"),
          # plot.background = element_rect(fill = "#f5f5f2", color = NA),
          # panel.background = element_rect(fill = "#f5f5f2", color = NA),
          # legend.background = element_rect(fill = "#f5f5f2", color = NA),
          plot.title = element_text(size = 22,
                                    hjust = 0.01, 
                                    # color = "#4e4d47",
                                    margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
          plot.subtitle = element_text(size= 17, 
                                       hjust=0.01,
                                       # color = "#4e4d47",
                                       margin = margin(b = -0.1, t = 0.43, l = 2, unit = "cm")),
          plot.caption = element_text(size=12, color = "#4e4d47", margin = margin(b = 0.3, r = -99, unit = "cm")),
          legend.position = c(0.7, 0.09)) +
    coord_map()
}
```

# Population counts per county

```{r subset-data}
pop <- data$census_population
pop$popestimate2010 <- NULL
colnames(pop)[7:ncol(pop)] <- gsub("census|pop|popestimate", "", colnames(pop)[7:ncol(pop)])
```


```{r density-all-preview-pop}
pop %>%
  drop_na() %>%
  pivot_longer(cols = 7:ncol(pop), names_to = "year") %>%
  group_by(fips) %>%
  arrange(year, .by_group = TRUE) %>%
  mutate(pct_dif = value/lag(value) * 100) %>%
  filter(!is.na(pct_dif)) %>%
  group_by(fips) %>%
  summarise(fips, abbrv, state, county, region, division, year, pct_avg = sum(pct_dif) / 9) %>%
  # filter(year == 2019) %>%
  ggplot(aes(pct_avg)) +
  geom_density() +
  labs(title = "Distribution percentage values", subtitle = "Values are average population change year to year", x = "Percentage value", y = "Density of value")
  # scale_x_continuous(trans = "log2")
```

```{r density-prc-per-state}
pop %>%
  drop_na() %>%
  pivot_longer(cols = 7:ncol(pop), names_to = "year") %>%
  group_by(fips) %>%
  arrange(year, .by_group = TRUE) %>%
  mutate(pct_dif = value/lag(value) * 100) %>%
  filter(!is.na(pct_dif)) %>%
  group_by(fips) %>%
  summarise(fips, abbrv, state, county, region, division, year, pct_avg = sum(pct_dif) / 9) %>%
  # filter(year == 2019) %>%
  ggplot(aes(pct_avg, group = abbrv, fill = abbrv, colour = abbrv)) +
  geom_density() +
  labs(title = "Distribution percentage values per state's county", subtitle = "Values are average population change year to year", x = "Percentage value", y = "Density of value") +
  facet_wrap(~ region, scales = "free")
```



```{r pivot-data-join-map}
pop_pct_diff <- pop %>% 
  drop_na() %>%
  pivot_longer(cols = 7:ncol(pop), names_to = "year") %>%
  group_by(fips) %>%
  arrange(year, .by_group = TRUE) %>%
  mutate(pct_dif = value/lag(value) * 100) %>%
  filter(!is.na(pct_dif)) %>%
  group_by(fips) %>%
  mutate(pct_avg = sum(pct_dif) / 9)

usa_pop <- usa_tdy %>%
  mutate(fips = as.numeric(id)) %>%
  left_join(pop_pct_diff, by = c("fips" = "fips"))

usa_pop$pct_avg[is.na(usa_pop$pct_avg)] <- 0.001

# usa_pop %>%
#   ggplot() +
#   geom_polygon(aes(fill = pct_avg, x = long, y = lat, group = group)) +
#   theme_void() +
#   coord_map()
```

```{r bar-pop-pct-diff}
pop_pct_diff %>%
  ggplot(aes(pct_avg)) +
  geom_histogram()
```


```{r choro-pop-pct-diff}
usa_pop %>%
	ggplot() +
	# geom_polygon(aes(fill = prc_chng, x = long, y = lat, group = group), size = 0, alpha = 0.9) +
  geom_polygon(aes(x = long, y = lat, group = group, fill = pct_avg), colour = "black", size = 0.075, alpha = 0.9) +
	theme_void() +
	coord_map() +
	scale_fill_viridis(n.breaks = 10, guide = guide_legend(keyheight = unit(3, units = "mm"), keywidth = unit(5, units = "mm"), nrow = 5), labels = function(x) {
		paste0(x, "%")
	}) + # label.position = "bottom", title.position = "top"
	labs(title = "Average percent change in population per county 2010 - 2019", caption = "By Dereck de Mezquita", fill = element_blank()) +
	theme(plot.title = element_text(size = 15, hjust = 0.01, margin = margin(r = 10, l = 2, b = 0.5, unit = "cm")), plot.caption = element_text(margin = margin(15, 50, unit = "mm")), legend.position = c(0.5, -0.075))
```


```{r}
gdp <- data$gdp_2001_2019
# colnames(gdp)[5:ncol(gdp)] <- gsub("x", "", colnames(gdp)[5:ncol(gdp)])

gdp %>%
  drop_na() %>%
  pivot_longer(cols = 5:ncol(gdp), names_to = "year") %>%
  mutate(year = as.numeric(gsub("X", "", year))) %>%
  filter(year == 2019) %>%
  ggplot(aes(value)) +
  geom_histogram(bins = 20) +
  scale_x_continuous(trans = "log2")

gdp2019 <- gdp %>%
  # drop_na() %>%
  pivot_longer(cols = 5:ncol(gdp), names_to = "year") %>%
  mutate(year = as.numeric(gsub("X", "", year))) %>%
  filter(year == 2019)
  # mutate(char_fips = as.character(fips))

usa_gdp <- usa_tdy %>%
  mutate(fips = as.numeric(id)) %>%
  left_join(gdp2019, by = c("fips" = "fips"))

usa_gdp$value[is.na(usa_gdp$value)] <- 0.001
```


```{r choro-gdp-test}
usa_gdp %>%
  ggplot() +
  geom_polygon(aes(fill = value, x = long, y = lat, group = group)) +
  theme_void() +
  coord_map()
```

```{r}
gdp2019 %>%
  ggplot(aes(log2(log2(value)))) +
  geom_histogram() +
  scale_x_continuous(labels = function(x) {
    scales::label_number_si(accuracy = 0.1)(x ^ (x ^ 2))
  })

max(gdp2019$value[!is.na(gdp2019$value)]); min(gdp2019$value[!is.na(gdp2019$value)])
```


```{r choro-gdp-2019, fig.height=8, fig.width=10}
usa_gdp %>%
	ggplot() +
	geom_polygon(aes(x = long, y = lat, group = group, fill = log10(log10(value))), colour = "black", size = 0.075, alpha = 0.9) +
	theme_void() +
	coord_map() +
	scale_fill_viridis(n.breaks = 10, guide = guide_legend(keyheight = unit(3, units = "mm"), name = "log10(log10(x))", keywidth = unit(5, units = "mm"), nrow = 5), labels = function(x) {
	  # format(x, big.mark = ",", scientific = FALSE)
	  scales::label_number_si(accuracy = 0.1)(x)
		# paste0(x, "%")
	}) + # label.position = "bottom", title.position = "top"
	labs(title = "GDP per county 2019", subtitle = "", caption = "By Dereck de Mezquita", fill = element_blank()) +
	theme(plot.title = element_text(size = 15, hjust = 0.01, margin = margin(r = 10, l = 2, b = 0.5, unit = "cm")), plot.caption = element_text(margin = margin(15, 50, unit = "mm")), legend.position = c(0.5, -0.075))
```


```{r}
usa_gdp %>%
  ggplot() +
  geom_polygon(aes(x = long, y = lat, group = group, fill = value), colour = "black", size = 0.075, alpha = 0.9) +
  # geom_polygon(aes(x = long, y = lat, group = group), size = 0.075, colour = "black", alpha = 0) +
  theme_void() +
  scale_fill_viridis(trans = "log10",
                     breaks = seq(0, max(usa_gdp$value), length.out = 5), # seq(0, max(usa_pop$value), by = 1000000)
                     name = "Population per county",
                     guide = guide_legend(keyheight = unit(2, units = "mm"), 
                                          keywidth = unit(3, units = "mm"), 
                                          label.position = "bottom", 
                                          title.position = 'top', 
                                          nrow = 1),
                     label = function(x) {
                       format(x, big.mark = ",", scientific = FALSE)
                     }) +
  labs(title = "GDP per county",
       # subtitle = "Population per county",
       caption = "Data: CENSUS BUREAU | By: Dereck | derecksnotes.com") +
  theme(text = element_text(color = "#22211d"),
        # plot.background = element_rect(fill = "#f5f5f2", color = NA),
        # panel.background = element_rect(fill = "#f5f5f2", color = NA),
        # legend.background = element_rect(fill = "#f5f5f2", color = NA),
        plot.title = element_text(size = 22,
                                  hjust = 0.01, 
                                  # color = "#4e4d47",
                                  margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
        plot.subtitle = element_text(size= 17, 
                                     hjust=0.01,
                                     # color = "#4e4d47",
                                     margin = margin(b = -0.1, t = 0.43, l = 2, unit = "cm")),
        plot.caption = element_text(size=12, color = "#4e4d47", margin = margin(b = 0.3, r = -99, unit = "cm")),
        legend.position = c(0.7, 0.09)) +
  coord_map()
```


```{r eval=FALSE}
pop2019 %>%
  count(state) %>%
  ggplot(aes(state, n, fill = state)) +
  geom_bar(stat = "identity") +
  labs(title = "Number of counties per state", x = "State", y = "Number of counties") +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90, vjust = 0, hjust = 1))
  # scale_x_continuous(trans = "log2")
```


```{r}
leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
```



```{r eval=FALSE}
pop %>%
  ggplot(aes(year, value)) +
  geom_line(aes(group = fips))
```



# Birth and death rate

```{r eval=FALSE}
rbind(data$census_births, data$census_deaths)
```

```{r eval=FALSE}
p <- birth_death %>% 
  drop_na() %>%
  # filter(abbrv == "LA") %>%
  pivot_longer(cols = c(starts_with("deaths"))) %>% # , starts_with("deaths")
  separate(name, c("type", "year"), "s") %>%
  ggplot(aes(x = year, y = value)) +
  geom_line(aes(group = fips, colour = fips)) +
  theme(legend.position = "none")
  # scale_y_continuous(trans = "log2")

ggplotly(p)
```




```{r eval=FALSE}
data$all_merged_data %>%
  filter(county == "Stanislaus")

data$all_merged_data$deaths2015 %>% 
  drop_na() %>%
  sum()
```

