---
title: 'USA: state and county level analysis'
author: "Dereck de Mézquita"
date: "`r format(Sys.time(), '%d %B, %Y')`"
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), "./reports/", "/us-state-county-analysis/us-state-county-analysis.html")) })
output:
  html_document: 
    fig_caption: yes
    keep_md: yes
    number_sections: yes
    toc: yes
    # toc_float: yes
    # code_folding: hide
params:
  rmd: us-state-county-analysis.Rmd
editor_options: 
  chunk_output_type: inline
---

<a download="us-state-county-analysis.Rmd" href="`r base64enc::dataURI(file = params$rmd, mime = 'text/rmd', encoding = 'base64')`">R Markdown source file (to produce this document)</a>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dpi = 500, fig.width = 8, fig.height = 8, fig.align = "center")
```

# Libraries

```{r libraries, warning=FALSE, message=FALSE}
library("tidyverse")
library("ddplot")
```

# ggplot theme

```{r set-ggplot-defaults}
update_geom_defaults("line", list(alpha = 0.65, size = 0.65))

theme_set(theme_dereck())
```

# Load data

```{r load-data}
data <- readRDS("./outputs/united-states-of-america/all_merged_data.Rds")
```

# County level

```{r}
data %>%
	ggplot(aes())
```


