---
title: "Exploratory analysis"
author: "Dereck de Mézquita"
date: "12/5/2020"
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), "./reports/", "us-vote-exploratory-analysis/us-vote-exploratory-analysis.html")) })
output:
  html_document: 
    fig_caption: yes
    keep_md: yes
    number_sections: yes
    toc: yes
    # toc_float: yes
params:
  rmd: us-vote-exploratory-analysis.Rmd
editor_options: 
  chunk_output_type: inline
---

<a download="us-vote-exploratory-analysis.Rmd" href="`r base64enc::dataURI(file = params$rmd, mime = 'text/rmd', encoding = 'base64')`">R Markdown source file (to produce this document)</a>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dpi = 500, fig.width = 8, fig.height = 8, fig.align = "center") #  out.width = "100%", out.height = "60vh"
```

# Libraries

```{r warning=FALSE, message=FALSE}
library("tidyverse")
# Suppress summarise info
options(dplyr.summarise.inform = FALSE)
library("plotly")
library("ggridges")
```

# Kaggle

```{r}
data <- lapply(list.files("./data/united-states-of-america/per-county-votes-20-fontes/", full.names = TRUE), read.csv)
names(data) <- gsub(".csv", "", list.files("./data/united-states-of-america/per-county-votes-20-fontes/"), perl = TRUE)
```

# Data

```{r}
names(data)
```

# Parameters

```{r}
clr <- list(
	rouge = "#e32b2b",
	bleu = "#2b5ce3",
	neutre = "#777777"
)
```


# Presidential election 2020

## Processing data

```{r}
# data$president_county
# data$president_county_candidate
# data$president_state
```

```{r}
data$president_county_candidate <- data$president_county_candidate %>%
	mutate(party = ifelse(party %in% c("REP", "DEM"), party, "Other"),
			 colour = case_when(party == "REP" ~ clr$rouge, party == "DEM" ~ clr$bleu, TRUE ~ clr$neutre),
			 county = gsub(" County", "", county)) %>%
	left_join(data.frame(abbrv = state.abb, state = state.name), by = "state"); # data$president_county_candidate
```

```{r}
data$president_county_candidate %>%
	group_by(county) %>%
	summarise(n())
```

```{r}
data$president_county_candidate %>%
	group_by(party) %>%
	summarise(`Total votes` = sum(total_votes)) %>%
	mutate(colour = case_when(party == "REP" ~ clr$rouge, party == "DEM" ~ clr$bleu, TRUE ~ clr$neutre)) %>%
	ggplot(aes(reorder(party, -`Total votes`), `Total votes`, fill = colour)) +
	geom_bar(stat = "identity") +
	scale_fill_identity(guide = "legend") +
	scale_y_continuous(n.breaks = 10, labels = function(x) {
		format(x, big.mark = ",", scientific = FALSE)
	}) +
	theme(legend.position = "none")
	# scale_y_continuous(trans = "log2", n.breaks = 10, labels = function(x) {format(signif(x, digits = 3), scientific = TRUE)})
```

```{r}
data$president_county_candidate %>%
	group_by(party) %>%
	summarise(`Total votes` = sum(total_votes)) %>%
	mutate(colour = case_when(party == "REP" ~ clr$rouge, party == "DEM" ~ clr$bleu, TRUE ~ clr$neutre)) %>%
	ggplot(aes(1, `Total votes`, fill = colour)) +
	geom_bar(stat = "identity", position = "fill") + # position = "fill", "stack"
	scale_fill_identity(guide = "legend") +
	scale_y_continuous(breaks = c(0, 0.25, 0.50, 0.75, 1.00), labels = c("0%", "25%", "50%", "25%", "0%")) +
	labs(x = "Parties", y = "Proportion of votes (%)") +
	theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
	theme(legend.position = "none")

# ggplotly(p, tooltip = c("x", "y", "text"))
```


```{r}
data$president_county_candidate %>%
	arrange(desc(total_votes)) %>%
	head(200) %>%
	mutate(state = factor(state),
			 state_county = paste(abbrv, county, sep = ": ")) %>%
	ggplot(aes(reorder(state_county, total_votes), total_votes, fill = colour)) +
	geom_bar(stat = "identity", position = "fill", width = 0.75) +
	scale_fill_identity(guide = "legend") +
	scale_y_continuous(breaks = c(0, 0.25, 0.50, 0.75, 1.00), labels = c("0%", "25%", "50%", "25%", "0%")) +
	# theme(axis.text.x = element_text(angle = 90, vjust = 0, hjust = 1)) +
	coord_flip() +
	theme(legend.position = "none") +
	labs(x = "State and County", y = "Proportion of votes (%)")

# ggplotly(p)


# data$president_county_candidate %>%
# 	arrange(desc(total_votes)) %>%
# 	group_by(state) %>%
# 	slice(head(row_number(), 1)) %>%
# 	mutate(state = factor(state),
# 			 state_county = paste(abbrv, county, sep = ": ")) %>%
# 	ggplot(aes(state_county, total_votes, group = state, fill = colour)) +
# 	geom_bar(stat = "identity", position = "fill") +
# 	scale_fill_identity(guide = "legend") +
# 	theme(axis.text.x = element_text(angle = 90, vjust = 0.85, hjust = 1)) 
# 	# facet_wrap(~ state)
```


```{r}
data$president_county_candidate %>%
	filter(total_votes != 0) %>%
	ggplot(aes(total_votes, ..density.., fill = colour)) +
	geom_density(alpha = 0.65) +
	scale_fill_identity(guide = "legend") +
	scale_y_continuous(n.breaks = 10, labels = function(x) {
		format(x, big.mark = ",", scientific = FALSE)
	}) +
	scale_x_continuous(trans = "log2", n.breaks = 20, labels = function(x) {
		format(x, big.mark = ",", scientific = FALSE)
	}) +
	theme(axis.text.x = element_text(angle = 45, vjust = 0.85, hjust = 1))  +
	theme(legend.position = "none")
	# facet_grid(state ~ .)
	
# data$president_county_candidate %>%
# 	filter(total_votes != 0) %>%
# 	ggplot(aes(total_votes, ..count.., fill = colour)) +
# 	geom_density(alpha = 0.65) +
# 	scale_fill_identity(guide = "legend") +
# 	scale_y_continuous(n.breaks = 10, labels = function(x) {
# 		format(x, big.mark = ",", scientific = FALSE)
# 	}) +
# 	scale_x_continuous(trans = "log2", n.breaks = 20, labels = function(x) {
# 		format(x, big.mark = ",", scientific = FALSE)
# 	}) +
# 	theme(axis.text.x = element_text(angle = 45, vjust = 0.85, hjust = 1)) +
# 	theme(legend.position = "none")
```

```{r fig.width=10, fig.height=20}
data$president_county_candidate %>%
	filter(total_votes != 0) %>%
	ggplot(aes(x = total_votes, y = state, fill = colour, height = ..density..)) +
	geom_density_ridges(alpha = 0.65, scale = 4, stat = "density") +
	scale_fill_identity(guide = "legend") +
	scale_x_continuous(trans = "log2") +
	theme_ridges() + 
	theme(legend.position = "none") +
	labs(x = "Vote count", y = "State")

# data$president_county_candidate %>%
# 	filter(total_votes != 0) %>%
# 	ggplot(aes(x = total_votes, y = state, fill = colour)) +
# 	geom_density_ridges(alpha = 0.65, scale = 2) +
# 	scale_fill_identity(guide = "legend") +
# 	scale_x_continuous(trans = "log2") +
# 	theme_ridges() + 
# 	theme(legend.position = "none")
```



```{r}
data$president_county_candidate %>%
	mutate(party = ifelse(party %in% c("REP", "DEM"), party, "Other")) %>%
	# arrange(desc(total_votes)) %>%
	# mutate(party = factor(party, levels = unique(party))) %>%
	group_by(state, party) %>%
	summarise(`Total votes` = sum(total_votes)) %>%
	mutate(colour = case_when(party == "REP" ~ clr$rouge, party == "DEM" ~ clr$bleu, TRUE ~ clr$neutre)) %>%
	ggplot(aes(x = state, y = `Total votes`, group = party, fill = colour, text = format(`Total votes`, big.mark = ",", scientific = FALSE))) +
	scale_fill_identity(guide = "legend") +
	geom_bar(stat = "identity", position = "fill") + # position = "fill", "stack"
	# theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
	labs(x = "State", y = "Proportion of votes (%)") +
	scale_y_continuous(breaks = c(0, 0.25, 0.50, 0.75, 1.00), labels = c("0%", "25%", "50%", "25%", "0%")) +
	theme(legend.position = "none") +
	coord_flip()

# ggplotly(p, tooltip = c("x", "y", "text"))
```

# Five thirty eight

```{r}
data <- lapply(list.files("./data/united-states-of-america/election-forecasts-2020-fivethirtyeight/", full.names = TRUE), read.csv)
names(data) <- gsub(".csv", "", list.files("./data/united-states-of-america/election-forecasts-2020-fivethirtyeight/"), perl = TRUE)
```

```{r}
data$README.md <- NULL
names(data)
```

```{r}
data$economic_index
```

